name: Github Pages Deploy

on: [push]

jobs:
  build-and-deploy:
    runs.on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and build
        run: npm install && npm run build

      -name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action sh
